### ISSUE TITLE
shinyproxy 2.4.0 loses reactivity when containerized

### ISSUE THREAD

**Issue by shosaco** [openanalytics/shinyproxy#241]
Shinyproxy 2.4.0. running in docker containers cause shiny apps to lose reactivity - only with shinyproxy 2.4.0, not with previous versions. 

The issue can be experienced by applying the following example:

[https://github.com/openanalytics/shinyproxy-config-examples/tree/master/02-containerized-docker-engine](https://github.com/openanalytics/shinyproxy-config-examples/tree/master/02-containerized-docker-engine)

Replacing `2.4.0` in the `Dockerfile` with `2.3.1` does not experience the same issue - everything works as expected with 2.3.1.

Attached are two screen captures demonstrating the issue with v2.3.0´1 and v.2.4.0, respectively.

Thanks and kind regards
sandro
![2 4 0](https://user-images.githubusercontent.com/20717764/96588384-df68de00-12e3-11eb-92bb-fd4b108257ab.gif)
![2 3 1](https://user-images.githubusercontent.com/20717764/96588385-e0017480-12e3-11eb-9cab-95398fe63460.gif)

**Comment by tverbeke** [comment]
Thanks for reporting, @shosaco ! We will investigate.

**Comment by LEDfan** [comment]
Thanks for you report. This has the same cause as #239 .
I'll update the repo and official images soon. In the meantime you can change this line https://github.com/openanalytics/shinyproxy-config-examples/blob/master/02-containerized-docker-engine/Dockerfile#L1 to `FROM openjdk:11-jre`

**Comment by LEDfan** [comment]
We just released [https://shinyproxy.io/downloads/#241](ShinyProxy 2.4.1) which is now again built using JDK 8.
I close this issue now, but don't hesitate to open a new issue if you encounter a new issue!

**Comment by xperimental** [comment]
Just ran into this issue myself and was happy to see that a new version was already released.

Unfortunately it seems to me like 2.4.1 still does not work properly on JDK8, because it still uses the containerproxy 0.8.5 version which, for me, was causing the issue in the first place (see below).

Can you check if the jar contained in the current release was actually built using JDK8 and, if not, release a fixed version with the dependency also built using JDK8 (probably a 0.8.6 then)?

I'll try using Java11 in the meantime, I'd actually prefer this to run on the newer JVM, but was not sure if this was a supported configuration.

```
2020-10-21 12:11:26.701 ERROR 19 --- [   XNIO-1 I/O-2] org.xnio.listener                        : XNIO001007: A channel event listener threw an exception

java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at eu.openanalytics.containerproxy.util.DelegatingStreamSourceConduit.read(DelegatingStreamSourceConduit.java:117) ~[containerproxy-0.8.5.jar!/:0.8.5]
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127) ~[xnio-api-3.8.0.Final.jar!/:3.8.0.Final]
	at io.undertow.util.Transfer$TransferListener.handleEvent(Transfer.java:212) ~[undertow-core-2.1.4.Final.jar!/:2.1.4.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.0.Final.jar!/:3.8.0.Final]
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) [xnio-api-3.8.0.Final.jar!/:3.8.0.Final]
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89) [xnio-nio-3.8.0.Final.jar!/:3.8.0.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591) [xnio-nio-3.8.0.Final.jar!/:3.8.0.Final]
```

**Comment by LEDfan** [comment]
Hi @xperimental 

Thanks for reaching out! The fact that it is still using ContainerProxy 0.8.5 is no problem, since no changes to the code had to be made. However, there was some problem with rebuilding the packages using JDK 8. 
This is now fixed and I uploaded new packages to the shinyproxy website, using version number 2.4.1
For reference this is the sha256sum of the working version `12ba6366f0d44859b4cd8dbc8469183d0eab1db1d87dffa4bb5a7d9db53bd583`

**Comment by xperimental** [comment]
In that case the file [in the releases](https://github.com/openanalytics/shinyproxy/releases/tag/v2.4.1) is not the correct one, because it's shasum differs:

```
> shasum -a 256 shinyproxy-2.4.1.jar
d1eb75bab9470cef60c6086f2aab4df41bbe81daf00147f1cb0089257dfee565  shinyproxy-2.4.1.jar
```

This is also the SHA256 checksum mentioned in the `shinyproxy-2.4.1.jar.sha256` file.

**Comment by LEDfan** [comment]
Thanks for the heads up, these were forgotten during the rebuilds....
The correct version is now also available at Github releases.
